services:
  - type: web
    name: sahhab-pro-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
